src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use function Symfony\Component\String\u;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'users')]
#[UniqueEntity(fields: ['email'], message: 'This email already exists.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $id;

    #[ORM\Column(type: 'string', length: 63, unique: true)]
    private string $email;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: 'string')]
    private string $password;

    #[ORM\Column(type: 'boolean')]
    private bool $isVerified = false;

    #[ORM\Column(type: 'string', length: 31)]
    private string $firstName;

    #[ORM\Column(type: 'string', length: 31)]
    private string $lastName;

    #[ORM\Column(type: 'string', length: 10)]
    private string $phoneNumber;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Booking::class)]
    private Collection $bookings;

    public function getFullName(): string
    {
        return u($this->getFirstName().' '.$this->getLastName())->title(true);
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setUser($this);
        }

        return $this;
    }

    /**
     * @return $this
     */
    public function removeBooking(Booking $booking): self
    {
        // set the owning side to null (unless already changed)
        if ($this->bookings->removeElement($booking) && $booking->getUser() === $this) {
            $booking->setUser(null);
        }

        return $this;
    }

    public function getFirstName(): string
    {
        return $this->firstName;
    }

    /**
     * @return $this
     */
    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): string
    {
        return $this->lastName;
    }

    /**
     * @return $this
     */
    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }

    /**
     * @return $this
     */
    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getUsername()
    {
        // TODO: Implement getUsername() method.
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Le Cosy Vendéen - Maison de vacances à St-Jean-De-Monts{% endblock %}</title>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/footer.html.twig
{% block body %}
    <footer id="footer" class="">
        ©2020 - {{ "now"|date("Y") }} Cornec
    </footer>
{% endblock %}

templates/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'navbar.html.twig' %}
    <div class="d-flex flex-wrap-reverse">
        <div class="p-2">
            <h4>Liens utiles</h4>
            <p><a href="https://www.saintjeandemonts.fr/" target="_blank">Mairie de Saint-Jean-de-Monts</a></p>
            <p><a href="https://www.saint-jean-de-monts.com/" target="_blank">Office de Tourisme</a></p>
            <p><a href="https://www.golfsaintjeandemonts.fr/" target="_blank">Golf</a></p>
            <p><a href="http://www.thalasso.com/thalasso/les-destinations/saint-jean-de-monts" target="_blank">Thalasso</a></p>
        </div>
        <div id="center-content" class="p-2 flex-grow-1">
            <turbo-frame id="content" src="{{ path('welcome') }}">
                <div class="text-center text-primary m-5">
                    <div class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </div>
            </turbo-frame>
        </div>
    </div>
    <div class="p-4"></div>
    {% include 'footer.html.twig' %}
{% endblock %}

templates/navbar.html.twig
{% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent" {{ stimulus_controller('navbar') }}>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a data-navbar-target="pages" class="nav-link active" href="{{ path('welcome') }}" data-turbo-frame="content" data-action="click->navbar#changeActive">
                            Accueil
                        </a>
                    </li>
                    <li class="nav-item">
                        <a data-navbar-target="pages" class="nav-link" aria-current="page" href="{{ path('presentation') }}" data-turbo-frame="content" data-action="click->navbar#changeActive">
                            Présentation
                        </a>
                    </li>
                    <li class="nav-item">
                        <a data-navbar-target="pages" class="nav-link" href="{{ path('booking') }}" data-turbo-frame="content" data-action="click->navbar#changeActive">
                            Réservation
                        </a>
                    </li>
                    {% if app.user %}
                    <li class="nav-item">
                        <a data-navbar-target="pages" class="nav-link" href="{{ path('my-bookings') }}" data-turbo-frame="content" data-action="click->navbar#changeActive">
                            Mes réservations
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a data-navbar-target="pages" class="nav-link" href="{{ path('about') }}" data-turbo-frame="content" data-action="click->navbar#changeActive">
                            À Propos
                        </a>
                    </li>
                    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_SUPER_ADMIN')%}
                    <li class="nav-item">
                        <a data-navbar-target="pages" class="nav-link" href="{{ path('admin_booking') }}" data-turbo-frame="content" data-action="click->navbar#changeActive">
                            Administration
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav mr-auto">
                {% if app.user %}
                    <li class="nav-item">
                        <div class="nav-link disabled" tabindex="-1" aria-disabled="true">
                            Bonjour {{ app.user.fullName }}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a data-navbar-target="pages" class="nav-link" data-turbo-frame="content" data-action="click->navbar#changeActive" href="{{ path('edit-profile') }}">
                            Mon Compte
                        </a>
                    </li>
                    <li class="nav-item">
                        <a data-navbar-target="pages" class="nav-link" href="{{ path('logout') }}">
                            Se déconnecter
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a data-navbar-target="pages" class="nav-link" href="{{ path('register') }}" data-turbo-frame="content" data-action="click->navbar#changeActive">
                            S'inscrire
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('login') }}">
                            Se Connecter
                        </a>
                    </li>
                {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}